<%@ Page Language="C#" AutoEventWireup="true" CodeFile="b_book_list.aspx.cs" Inherits="book_data_b_book_list" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
<<<<<<< HEAD
    <link href="../css/self-style.css" rel="stylesheet" />
    <link href="../css/button_broder.css" rel="stylesheet" />
    <style type="text/css">
        .auto-style3 {
            width: 489px;
            height: 351px;
            margin: 10px auto;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="auto-style3">
            <asp:GridView ID="GridView1" runat="server" CellPadding="4" ForeColor="#333333"   GridLines="None" Width="475px"
                 AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting" DataKeyNames="订单编号" Height="339px" >
                <AlternatingRowStyle BackColor="White" />
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
                
                
            </asp:GridView>
       
        </div>

        <a>&nbsp;</a>

        <div class="mid-style">
            <asp:Button ID="Button1" runat="server" Text="返回" OnClick="Button1_Click" CssClass="auto-style1" Height="40px" Width="190px" />
=======
</head>
<body>
    <form id="form1" runat="server">
        <div style="width:300px;margin: 10px auto;">
            <asp:GridView ID="GridView1" runat="server" ></asp:GridView>
        </div>
        <div style="width:300px;margin: 10px auto;">
            <asp:Button ID="Button1" runat="server" Text="返回" OnClick="Button1_Click" />
>>>>>>> 0e4ab70293e60bf39dace0390b1f92eebb580049
        </div>
    </form>
</body>
</html>
